import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:image/image.dart' as img;

import '../models/generated_gcode.dart';

class ImageToGcodeException implements Exception {
  const ImageToGcodeException(this.message);

  final String message;

  @override
  String toString() => message;
}

class ImageToGcodeConverter {
  const ImageToGcodeConverter._();

  static Future<GeneratedGcode> convert({
    required Uint8List imageBytes,
    required ImageGcodeSettings settings,
  }) async {
    final result = await compute(_convertImageToGcodeTask, {
      'bytes': imageBytes,
      'settings': settings.toJson(),
    });

    return GeneratedGcode.fromJson(Map<String, dynamic>.from(result));
  }
}

Map<String, dynamic> _convertImageToGcodeTask(Map<String, dynamic> args) {
  final bytes = args['bytes'];
  if (bytes is! Uint8List || bytes.isEmpty) {
    throw const ImageToGcodeException('الصورة فاضية أو غير مقروءة');
  }

  final settings = ImageGcodeSettings.fromJson(
    Map<String, dynamic>.from(args['settings'] as Map),
  );

  if (settings.safeWidthMm < 10 || settings.safeHeightMm < 10) {
    throw const ImageToGcodeException('Safe Area صغيرة جدًا. خلي العرض والارتفاع أكبر من 10 mm.');
  }
  if (settings.safeXmm < 0 || settings.safeYmm < 0) {
    throw const ImageToGcodeException('بداية Safe Area لازم تكون صفر أو أكبر.');
  }

  final decoded = img.decodeImage(bytes);
  if (decoded == null) {
    throw const ImageToGcodeException('نوع الصورة غير مدعوم');
  }

  final sourceWidth = decoded.width;
  final sourceHeight = decoded.height;
  final targetWidth = settings.rasterWidthPx.clamp(40, 420).toInt();
  final resized = img.copyResize(
    decoded,
    width: targetWidth,
    interpolation: img.Interpolation.average,
  );

  final rasterWidth = resized.width;
  final rasterHeight = resized.height;

  final aspect = rasterWidth / math.max(1, rasterHeight);
  final safeAspect = settings.safeWidthMm / math.max(1, settings.safeHeightMm);
  late final double usedWidthMm;
  late final double usedHeightMm;

  if (aspect >= safeAspect) {
    usedWidthMm = settings.safeWidthMm;
    usedHeightMm = settings.safeWidthMm / aspect;
  } else {
    usedHeightMm = settings.safeHeightMm;
    usedWidthMm = settings.safeHeightMm * aspect;
  }

  final xScale = rasterWidth <= 1 ? 0 : usedWidthMm / (rasterWidth - 1);
  final yScale = rasterHeight <= 1 ? 0 : usedHeightMm / (rasterHeight - 1);

  // Center the drawing inside the user-defined safe drawing rectangle.
  final xOffset = settings.safeXmm + ((settings.safeWidthMm - usedWidthMm) / 2);
  final yOffset = settings.safeYmm + ((settings.safeHeightMm - usedHeightMm) / 2);

  final lines = <String>[
    '; Generated by Spidy Draw mobile app',
    '; Mode: raster black/white image to G-code',
    '; Safe Area: X${settings.safeXmm.toStringAsFixed(2)} Y${settings.safeYmm.toStringAsFixed(2)} W${settings.safeWidthMm.toStringAsFixed(2)} H${settings.safeHeightMm.toStringAsFixed(2)} mm',
    'G21',
    'G90',
    'M5',
  ];
  final segments = <Map<String, dynamic>>[];
  var truncated = false;

  bool canAddSegment() {
    // Each drawn segment adds M5, G0, M3, G1, M5 = 5 commands.
    // Keep 3 commands free for footer/safety.
    return lines.length + 8 <= settings.maxCommands;
  }

  bool isBlack(int x, int y) {
    final pixel = resized.getPixel(x, y);
    final alpha = pixel.a.toDouble();
    if (alpha < 20) {
      return settings.invert;
    }

    final r = pixel.r.toDouble();
    final g = pixel.g.toDouble();
    final b = pixel.b.toDouble();
    final luma = (0.299 * r) + (0.587 * g) + (0.114 * b);
    final black = luma < settings.threshold;
    return settings.invert ? !black : black;
  }

  double mmX(int x) => xOffset + (x * xScale);
  double mmY(int y) => yOffset + (y * yScale);

  final rowStep = settings.rowStepPx.clamp(1, 12).toInt();
  final minRun = settings.minRunPx.clamp(1, 20).toInt();
  var rowIndex = 0;

  for (var y = 0; y < rasterHeight; y += rowStep) {
    final runs = <({int start, int end})>[];
    var x = 0;

    while (x < rasterWidth) {
      while (x < rasterWidth && !isBlack(x, y)) {
        x++;
      }
      if (x >= rasterWidth) break;

      final start = x;
      while (x < rasterWidth && isBlack(x, y)) {
        x++;
      }
      final end = x - 1;

      if (end - start + 1 >= minRun) {
        runs.add((start: start, end: end));
      }
    }

    final orderedRuns = rowIndex.isOdd ? runs.reversed : runs;
    for (final run in orderedRuns) {
      if (!canAddSegment()) {
        truncated = true;
        break;
      }

      final startX = rowIndex.isOdd ? mmX(run.end) : mmX(run.start);
      final endX = rowIndex.isOdd ? mmX(run.start) : mmX(run.end);
      final yMm = mmY(y);

      lines
        ..add('M5')
        ..add('G0 X${startX.toStringAsFixed(2)} Y${yMm.toStringAsFixed(2)}')
        ..add('M3')
        ..add('G1 X${endX.toStringAsFixed(2)} Y${yMm.toStringAsFixed(2)}')
        ..add('M5');

      if (segments.length < 2400) {
        segments.add({
          'startX': startX,
          'startY': yMm,
          'endX': endX,
          'endY': yMm,
        });
      }
    }

    if (truncated) break;
    rowIndex++;
  }

  // Keep the pen up and finish at the beginning of the safe rectangle,
  // not at machine zero, so the app does not add an unexpected outside-area move.
  lines
    ..add('M5')
    ..add('G0 X${settings.safeXmm.toStringAsFixed(2)} Y${settings.safeYmm.toStringAsFixed(2)}');

  return {
    'gcode': lines.join('\n'),
    'segments': segments,
    'commandCount': lines.where((line) => line.trim().isNotEmpty && !line.trim().startsWith(';')).length,
    'segmentCount': segments.length,
    'sourceWidth': sourceWidth,
    'sourceHeight': sourceHeight,
    'rasterWidth': rasterWidth,
    'rasterHeight': rasterHeight,
    'safeXmm': settings.safeXmm,
    'safeYmm': settings.safeYmm,
    'safeWidthMm': settings.safeWidthMm,
    'safeHeightMm': settings.safeHeightMm,
    'usedWidthMm': usedWidthMm,
    'usedHeightMm': usedHeightMm,
    'truncated': truncated,
  };
}
